### ISSUE TITLE
update website link on repository and organization

### ISSUE THREAD

**Issue by dinonil** [BracketsJS/BracketsJS#33]

**Comment by JaydenDev** [comment]
What do you mean? The link works.

**Comment by dinonil** [comment]
@JaydenDev ![Screenshot from 2022-07-02 15-31-52](https://user-images.githubusercontent.com/104044615/177014066-a3fb4d8b-f222-47b4-9597-c4a3425ba60b.png)

**Comment by JaydenDev** [comment]
@dinonil weird, try clearing  your cache it works for me.
